//! Renders `docs/COVERAGE.md` from the same registry data that serves
//! `GET /_config/coverage`, so the doc cannot drift from the mounted surface.
//!
//! Run from anywhere in the workspace: `cargo run -p gen-coverage`.

use std::fmt::Write as _;
use std::path::Path;

use serde_json::Value;
use zebrafish_server::config::coverage::coverage_json;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let matrix = coverage_json();
    let markdown = render(&matrix);

    // CARGO_MANIFEST_DIR = tools/gen-coverage — the repo root is two up.
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("tools/gen-coverage sits two levels under the repo root");
    let out = root.join("docs/COVERAGE.md");
    std::fs::create_dir_all(out.parent().expect("docs dir has a parent"))?;
    std::fs::write(&out, markdown)?;
    eprintln!("wrote {}", out.display());
    Ok(())
}

fn render(matrix: &Value) -> String {
    let mut md = String::new();
    let _ = writeln!(md, "# Coverage");
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "<!-- Generated by `cargo run -p gen-coverage` — do not edit by hand. -->"
    );
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "Stripe-compatible surface implemented by zebrafish, pinned to API version \
         `{}`. The same matrix is served live at `GET /_config/coverage`; anything \
         not listed answers with the 501 `not_implemented` envelope.",
        matrix["stripe_api_version"].as_str().unwrap_or("?"),
    );
    let _ = writeln!(md);
    let _ = writeln!(md, "## Resources");
    let _ = writeln!(md);
    let _ = writeln!(md, "| Resource | ID prefix | Routes | CRUD events |");
    let _ = writeln!(md, "| --- | --- | --- | --- |");

    for res in matrix["resources"].as_array().into_iter().flatten() {
        let routes = join(&res["routes"], "<br>");
        let events = join(&res["events"], "<br>");
        let _ = writeln!(
            md,
            "| `{}` | `{}` | {} | {} |",
            res["resource"].as_str().unwrap_or("?"),
            res["id_prefix"].as_str().unwrap_or("?"),
            routes,
            if events.is_empty() {
                "—".to_string()
            } else {
                events
            },
        );
    }

    let _ = writeln!(md);
    let _ = writeln!(md, "## Cascade fixtures");
    let _ = writeln!(md);
    let cascades = matrix["cascades"]
        .as_array()
        .map(Vec::as_slice)
        .unwrap_or_default();
    if cascades.is_empty() {
        let _ = writeln!(md, "None packaged yet (cascade fixtures land in WS-E).");
    } else {
        for c in cascades {
            let _ = writeln!(md, "- `{}`", c.as_str().unwrap_or("?"));
        }
    }
    md
}

fn join(v: &Value, sep: &str) -> String {
    v.as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(|s| format!("`{s}`"))
                .collect::<Vec<_>>()
                .join(sep)
        })
        .unwrap_or_default()
}
